import random

def gen_random():
    index = random.randint(0, len(spells) - 1)
    return spells[index]

spells = ('Accio',
          'Aguamenti',
          'Alohomora',
          'Anapneo',
          'Aparecium',
          'Avada Kedavra',
          'Avis',
          'Capacious Extremis',
          'Cave Inimicum',
          'Colloportus',
          'Confringo',
          'Confundo',
          'Crucio',
          'Defodio',
          'Deletrius',
          'Densaugeo',
          'Deprimo',
          'Descendo',
          'Diffindo',
          'Duro',
          'Engorgio',
          'Episkey',
          'Erecto',
          'Evanesco',
          'Expecto Patronum',
          'Expelliarmus',
          'Expulso',
          'Ferula',
          'Finite Incantatem',
          'Flagrate',
          'Furnunculus',
          'Geminio',
          'Glisseo',
          'Homenum Revelio',
          'Impedimenta',
          'Imperio',
          'Impervius',
          'Incarcerous',
          'Incendio',
          'Langlock',
          'Legilimens',
          'Levicorpus',
          'Liberacorpus',
          'Locomotor',
          'Locomotor Mortis',
          'Lumos',
          'Meteolojinx Recanto',
          'Mobiliarbus',
          'Mobilicorpus',
          'Morsmordre',
          'Muffliato',
          'Nox',
          'Obliviate',
          'Obscuro',
          'Oppugno',
          'Orchideous',
          'Pack',
          'Petrificus Totalus',
          'Piertotum Locomotor',
          'Point Me',
          'Portus',
          'Prior Incantato',
          'Protego',
          'Protego Horribilis',
          'Protego Totalum',
          'Quietus',
          'Reducio',
          'Reducto',
          'Relashio',
          'Rennervate',
          'Reparo',
          'Repello Muggletum',
          'Rictusempra',
          'Riddikulus',
          'Salvio Hexia',
          'Scourgify',
          'Sectumsempra',
          'Serpensortia',
          'Silencio',
          'Sonorus',
          'Specialis Revelio',
          'Stupefy',
          'Tarantallegra',
          'Tergeo',
          'Waddiwasi',
          'Wingardium Leviosa')
